spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    open-in-view: false

  data:
    redis:
      port: 6379
      host: localhost

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

jwt:
  secretKey: c2VjcmV0LWtleXNlY3JldC1rZXlzZWNyZXQta2V5c2VjcmV0LWtleXNlY3JldC1rZXlzZWNyZXQta2V5
  accessTokenExpirationPeriodDay: 1000000

sms:
  nhn:
    appKey: ""
    secretKey: ""
    sendNo: ""

oauth:
  apple:
    keyId: ""
    teamId: ""
    clientId: "애플 번들 ID"
    privateKeyFileName: "애플 private 등록 시 다운받은 p8 파일 이름 (p8) 포함"

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

swagger:
  server-url: http://localhost:8080

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json

aws:
  s3:
    bucket: my-bucket
    image-path: images/
    presigned-url-expires-minutes: 10

tosspayment:
  secret-key: "...:"

wincube:
  mdCode: "test"
  token: "token"
  auth:
    aut-key: "test"
    cust-id: "test"
    pwd: "test"
